// scripts/gen-tokens.mjs — design/design-system/tokens.json → src/theme/tokens.css.
//
//   node scripts/gen-tokens.mjs        # rewrite the CSS
//
// src/__tests__/tokens.test.ts re-renders and compares, so the two can't drift.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const TOKENS_JSON = join(root, "design/design-system/tokens.json");
export const TOKENS_CSS = join(root, "src/theme/tokens.css");

const kebab = (s) => s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());

/** Render the tokens file as CSS: one `--<name>` per token plus the `t-*` type classes. */
export function render(tokens) {
  const vars = [];
  for (const group of ["color", "spacing", "radius", "shadow", "size"])
    for (const t of tokens[group].tokens) vars.push(`  --${t.name}: ${t.value};`);
  for (const [name, value] of Object.entries(tokens.type.families))
    vars.push(`  --font-${name}: ${value};`);

  const classes = [];
  for (const g of tokens.type.groups)
    for (const s of g.styles) {
      const decl = [`font-family: var(--font-${g.family})`];
      for (const [k, v] of Object.entries(s))
        if (!["name", "sample", "usage"].includes(k)) decl.push(`${kebab(k)}: ${String(v)}`);
      classes.push(`.${s.name} { ${decl.join("; ")}; }`);
    }

  return [
    "/* Generated by scripts/gen-tokens.mjs from design/design-system/tokens.json. Do not edit. */",
    "",
    ":root {",
    "  color-scheme: dark;",
    ...vars,
    "}",
    "",
    ...classes,
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(TOKENS_CSS, render(JSON.parse(readFileSync(TOKENS_JSON, "utf8"))));
  console.log(`wrote ${TOKENS_CSS}`);
}
